INFO 2025-03-18 23:50:32,082 autoreload Watching for file changes with StatReloader
INFO 2025-03-18 23:50:45,775 basehttp "GET / HTTP/1.1" 200 3146
INFO 2025-03-18 23:50:52,996 basehttp "GET / HTTP/1.1" 200 3146
INFO 2025-03-18 23:50:56,146 basehttp "GET /1/ HTTP/1.1" 200 3163
INFO 2025-03-18 23:50:58,049 basehttp "GET / HTTP/1.1" 200 3146
INFO 2025-03-19 19:28:26,210 autoreload Watching for file changes with StatReloader
INFO 2025-03-19 19:28:37,587 basehttp "GET / HTTP/1.1" 200 3146
INFO 2025-03-19 19:28:41,275 basehttp "GET /accounts/login/ HTTP/1.1" 200 4557
INFO 2025-03-19 19:28:44,620 basehttp "GET /accounts/register/ HTTP/1.1" 200 5747
INFO 2025-03-19 19:28:46,387 basehttp "GET /accounts/login/ HTTP/1.1" 200 4557
INFO 2025-03-19 19:28:47,692 basehttp "GET / HTTP/1.1" 200 3146
INFO 2025-03-19 19:28:50,119 basehttp "GET /accounts/register/ HTTP/1.1" 200 5747
INFO 2025-03-19 19:29:24,123 basehttp "POST /accounts/register/ HTTP/1.1" 200 6025
INFO 2025-03-19 19:29:39,435 basehttp "POST /accounts/register/ HTTP/1.1" 200 5921
INFO 2025-03-19 19:29:50,677 basehttp "POST /accounts/register/ HTTP/1.1" 302 0
INFO 2025-03-19 19:29:50,698 basehttp "GET / HTTP/1.1" 200 3331
INFO 2025-03-19 19:29:56,694 basehttp "GET /1/ HTTP/1.1" 200 4494
INFO 2025-03-19 19:30:04,055 basehttp "POST /1/vote/ HTTP/1.1" 302 0
ERROR 2025-03-19 19:30:04,095 log Internal Server Error: /1/results/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/sg44574/Dropbox/Coding/polling-visualization/polls/views.py", line 56, in results
    total_votes = question.choice_set.aggregate(total=Sum('votes'))['total'] or 0
                                                      ^^^
NameError: name 'Sum' is not defined. Did you mean: 'sum'?
ERROR 2025-03-19 19:30:04,097 basehttp "GET /1/results/ HTTP/1.1" 500 78338
INFO 2025-03-19 19:43:22,575 basehttp "GET /1/ HTTP/1.1" 200 3542
ERROR 2025-03-19 19:43:25,685 log Internal Server Error: /1/results/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/sg44574/Dropbox/Coding/polling-visualization/polls/views.py", line 56, in results
    total_votes = question.choice_set.aggregate(total=Sum('votes'))['total'] or 0
                                                      ^^^
NameError: name 'Sum' is not defined. Did you mean: 'sum'?
ERROR 2025-03-19 19:43:25,686 basehttp "GET /1/results/ HTTP/1.1" 500 77943
INFO 2025-03-19 19:44:52,638 autoreload /Users/sg44574/Dropbox/Coding/polling-visualization/polls/views.py changed, reloading.
INFO 2025-03-19 19:44:53,209 autoreload Watching for file changes with StatReloader
INFO 2025-03-19 19:44:56,939 basehttp "GET /1/ HTTP/1.1" 200 3351
ERROR 2025-03-19 19:44:58,793 log Internal Server Error: /1/results/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/sg44574/Dropbox/Coding/polling-visualization/polls/views.py", line 58, in results
    return render(request, "polls/results.html", {
        "question": question,
        "total_votes": total_votes
    })
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
        (
    ...<2 lines>...
        )
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 1531, in do_with
    extra_context = token_kwargs(remaining_bits, parser, support_legacy=True)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 1119, in token_kwargs
    kwargs[key] = parser.compile_filter(value)
                  ~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 701, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 611, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'getattribute'
ERROR 2025-03-19 19:44:58,797 basehttp "GET /1/results/ HTTP/1.1" 500 240441
ERROR 2025-03-19 19:47:13,456 log Internal Server Error: /1/results/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/sg44574/Dropbox/Coding/polling-visualization/polls/views.py", line 58, in results
    return render(request, "polls/results.html", {
        "question": question,
        "total_votes": total_votes
    })
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
        (
    ...<2 lines>...
        )
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 1531, in do_with
    extra_context = token_kwargs(remaining_bits, parser, support_legacy=True)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 1119, in token_kwargs
    kwargs[key] = parser.compile_filter(value)
                  ~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 706, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '.votes' from 'question.choice_set.all|dictsort:"votes"|last.votes'
ERROR 2025-03-19 19:47:13,462 basehttp "GET /1/results/ HTTP/1.1" 500 235247
ERROR 2025-03-19 19:48:21,645 log Internal Server Error: /1/results/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/Users/sg44574/Dropbox/Coding/polling-visualization/polls/views.py", line 58, in results
    return render(request, "polls/results.html", {
        "question": question,
        "total_votes": total_votes
    })
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
        (
    ...<2 lines>...
        )
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 1540, in do_with
    nodelist = parser.parse(("endwith",))
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 1540, in do_with
    nodelist = parser.parse(("endwith",))
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 1531, in do_with
    extra_context = token_kwargs(remaining_bits, parser, support_legacy=True)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 1119, in token_kwargs
    kwargs[key] = parser.compile_filter(value)
                  ~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 701, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 611, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'div'
ERROR 2025-03-19 19:48:21,649 basehttp "GET /1/results/ HTTP/1.1" 500 290471
INFO 2025-03-19 19:50:23,750 basehttp "GET /1/results/ HTTP/1.1" 200 3486
INFO 2025-03-19 19:50:28,005 basehttp "GET /1/ HTTP/1.1" 200 3351
INFO 2025-03-19 19:50:31,964 basehttp "GET /1/ HTTP/1.1" 200 3351
INFO 2025-03-19 19:50:34,115 basehttp "GET /1/ HTTP/1.1" 200 3351
INFO 2025-03-19 19:50:35,406 basehttp "GET / HTTP/1.1" 200 3144
INFO 2025-03-19 19:50:37,718 basehttp "GET /1/ HTTP/1.1" 200 3351
INFO 2025-03-19 20:07:51,541 autoreload Watching for file changes with StatReloader
ERROR 2025-03-19 20:07:57,574 log Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/sg44574/Dropbox/Coding/polling-visualization/polls/views.py", line 39, in index
    return render(request, "polls/index.html", context)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'category' with arguments '('',)' not found. 1 pattern(s) tried: ['category/(?P<category>[^/]+)/\\Z']
ERROR 2025-03-19 20:07:57,579 basehttp "GET / HTTP/1.1" 500 166068
INFO 2025-03-19 20:12:30,965 autoreload /Users/sg44574/Dropbox/Coding/polling-visualization/polls/models.py changed, reloading.
INFO 2025-03-19 20:12:31,543 autoreload Watching for file changes with StatReloader
INFO 2025-03-19 20:14:36,746 autoreload /Users/sg44574/Dropbox/Coding/polling-visualization/polls/views.py changed, reloading.
INFO 2025-03-19 20:14:37,311 autoreload Watching for file changes with StatReloader
INFO 2025-03-19 20:15:00,442 autoreload /Users/sg44574/Dropbox/Coding/polling-visualization/polls/admin.py changed, reloading.
INFO 2025-03-19 20:15:00,949 autoreload Watching for file changes with StatReloader
INFO 2025-03-19 20:16:48,097 autoreload /Users/sg44574/Dropbox/Coding/polling-visualization/polls/views.py changed, reloading.
INFO 2025-03-19 20:16:48,672 autoreload Watching for file changes with StatReloader
INFO 2025-03-19 20:23:27,039 autoreload Watching for file changes with StatReloader
INFO 2025-03-19 20:23:30,979 basehttp "GET / HTTP/1.1" 200 11161
INFO 2025-03-19 20:23:47,956 basehttp "GET /dashboard/ HTTP/1.1" 200 6499
INFO 2025-03-19 20:23:53,419 basehttp "GET /1/results/ HTTP/1.1" 200 36088
INFO 2025-03-19 20:24:01,263 basehttp "GET /1/ HTTP/1.1" 200 8317
INFO 2025-03-19 20:24:04,085 basehttp "GET / HTTP/1.1" 200 11161
INFO 2025-03-19 20:24:08,754 basehttp "GET /6/ HTTP/1.1" 200 9879
INFO 2025-03-19 20:24:20,810 basehttp "POST /6/vote/ HTTP/1.1" 302 0
INFO 2025-03-19 20:24:20,895 basehttp "GET /6/results/ HTTP/1.1" 200 51143
INFO 2025-03-19 20:24:32,097 basehttp "GET / HTTP/1.1" 200 11161
INFO 2025-03-19 20:24:35,816 basehttp "GET /dashboard/ HTTP/1.1" 200 6875
INFO 2025-03-19 20:24:40,003 basehttp "GET / HTTP/1.1" 200 11161
WARNING 2025-03-19 20:24:44,187 base Method Not Allowed (GET): /accounts/logout/
WARNING 2025-03-19 20:24:44,188 log Method Not Allowed: /accounts/logout/
WARNING 2025-03-19 20:24:44,188 basehttp "GET /accounts/logout/ HTTP/1.1" 405 0
WARNING 2025-03-19 20:24:53,791 log Not Found: /accounts/
WARNING 2025-03-19 20:24:53,791 basehttp "GET /accounts/ HTTP/1.1" 404 6556
INFO 2025-03-19 20:24:58,724 basehttp "GET / HTTP/1.1" 200 11161
WARNING 2025-03-19 20:25:02,714 base Method Not Allowed (GET): /accounts/logout/
WARNING 2025-03-19 20:25:02,715 log Method Not Allowed: /accounts/logout/
WARNING 2025-03-19 20:25:02,715 basehttp "GET /accounts/logout/ HTTP/1.1" 405 0
INFO 2025-03-19 20:41:42,601 autoreload /Users/sg44574/Dropbox/Coding/polling-visualization/mysite/settings.py changed, reloading.
INFO 2025-03-19 20:41:43,208 autoreload Watching for file changes with StatReloader
INFO 2025-03-19 20:45:24,072 autoreload /Users/sg44574/Dropbox/Coding/polling-visualization/mysite/urls.py changed, reloading.
INFO 2025-03-19 20:45:24,726 autoreload Watching for file changes with StatReloader
INFO 2025-03-19 20:45:43,219 basehttp "GET / HTTP/1.1" 200 11161
WARNING 2025-03-19 20:45:47,008 base Method Not Allowed (GET): /accounts/logout/
WARNING 2025-03-19 20:45:47,027 log Method Not Allowed: /accounts/logout/
WARNING 2025-03-19 20:45:47,028 basehttp "GET /accounts/logout/ HTTP/1.1" 405 0
INFO 2025-03-19 20:47:00,463 autoreload /Users/sg44574/Dropbox/Coding/polling-visualization/mysite/urls.py changed, reloading.
INFO 2025-03-19 20:47:00,947 autoreload Watching for file changes with StatReloader
INFO 2025-03-19 20:48:01,645 basehttp "GET / HTTP/1.1" 200 11500
INFO 2025-03-19 20:48:06,906 basehttp "POST /accounts/logout/ HTTP/1.1" 302 0
INFO 2025-03-19 20:48:06,927 basehttp "GET / HTTP/1.1" 200 11154
INFO 2025-03-19 20:48:11,526 basehttp "GET /accounts/login/ HTTP/1.1" 200 7440
INFO 2025-03-19 20:48:18,791 basehttp "POST /accounts/login/ HTTP/1.1" 302 0
INFO 2025-03-19 20:48:18,812 basehttp "GET / HTTP/1.1" 200 11500
INFO 2025-03-19 20:50:19,640 basehttp "GET / HTTP/1.1" 200 11473
INFO 2025-03-19 20:50:56,861 basehttp "GET / HTTP/1.1" 200 11538
INFO 2025-03-19 20:51:08,490 basehttp "POST /accounts/logout/ HTTP/1.1" 302 0
INFO 2025-03-19 20:51:08,597 basehttp "GET / HTTP/1.1" 200 11154
INFO 2025-03-19 20:51:10,508 basehttp "GET /accounts/login/ HTTP/1.1" 200 7440
INFO 2025-03-19 20:51:19,889 basehttp "POST /accounts/login/ HTTP/1.1" 302 0
INFO 2025-03-19 20:51:19,909 basehttp "GET / HTTP/1.1" 200 11538
INFO 2025-03-19 20:51:26,484 basehttp "GET / HTTP/1.1" 200 11538
INFO 2025-03-19 20:51:28,714 basehttp "GET /dashboard/ HTTP/1.1" 200 6566
INFO 2025-03-19 20:51:31,826 basehttp "GET / HTTP/1.1" 200 11538
INFO 2025-03-19 21:00:42,442 autoreload /Users/sg44574/Dropbox/Coding/polling-visualization/mysite/settings.py changed, reloading.
INFO 2025-03-19 21:00:43,144 autoreload Watching for file changes with StatReloader
INFO 2025-03-19 21:01:20,596 autoreload /Users/sg44574/Dropbox/Coding/polling-visualization/mysite/wsgi.py changed, reloading.
INFO 2025-03-19 21:01:21,153 autoreload Watching for file changes with StatReloader
INFO 2025-03-19 21:01:26,948 basehttp "GET / HTTP/1.1" 200 11538
